SELECT DISTINCT(FUNCTION_ID) AS Id, B.NAME AS Name , b.Description 
FROM ROLE_FUNCTION A INNER JOIN [MENU] B ON A.FUNCTION_ID = B.ID AND A.APPLICATION = B.APPLICATION
WHERE ROLE_ID = @RoleId 
	AND a.APPLICATION = @Application