SELECT c.ID AS Id, c.[KEY] AS [Key] , c.Qualifier, a.DISPLAY AS AuthorizationUIPolicy
FROM ROLE_FUNCTION A INNER JOIN [MENU] B ON A.FUNCTION_ID = B.ID INNER JOIN FEATURE C ON a.FEATURE_ID = c.ID
	AND A.APPLICATION = B.APPLICATION
WHERE ROLE_ID = @RoleId AND b.ID = @FunctionId
	AND a.APPLICATION = @Application