DECLARE @@RoleId int	

SELECT @@RoleId = b.ROLE_ID
FROM USER_PROFILE a LEFT JOIN USER_ROLE b ON a.NETWORK_ID = b.NETWORK_ID AND a.APPLICATION = b.APPLICATION
WHERE (ISNULL(@Username, '') = '' OR (@Username IS NOT NULL AND a.NETWORK_ID = @Username))
	AND a.APPLICATION = @Application 

SELECT ID, NAME, DESCRIPTION FROM ROLE	
WHERE  ID = @@RoleId
	AND APPLICATION = @Application