DECLARE @@RoleId int	

SELECT @@RoleId = b.ROLE_ID
FROM USER_PROFILE a LEFT JOIN USER_ROLE b ON a.USERNAME = b.USERNAME
WHERE (ISNULL(@Username, '') = '' OR (@Username IS NOT NULL AND a.USERNAME = @Username))
	  
SELECT ID, NAME, DESCRIPTION FROM ROLE	
WHERE  ID = @@RoleId 