DECLARE @@userID NVARCHAR(50)

IF EXISTS (SELECT TOP 1 USERNAME FROM [USER_PROFILE] WHERE USERNAME=@Username)
BEGIN
    SET @@userID=(SELECT USERNAME FROM [USER_PROFILE] WHERE USERNAME=@Username AND PasswordHash=HASHBYTES('SHA2_512', @Password+CAST(Salt AS NVARCHAR(36))))

    IF(@@userID IS NOT NULL)          
        SELECT [USERNAME]
			  ,[FIRSTNAME]
			  ,[LASTNAME]
			  ,[EMAIL]
			  ,[STATUS] 
			  ,[ISBACKUP]  
			  ,[ISACTIVE] 
		  FROM [USER_PROFILE]
		  WHERE USERNAME = @Username
END 